# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Invidious
version: "1.4.0"
slug: invidious
description: Invidious - Privacy-friendly YouTube frontend
url: "https://github.com/tserra30/Invidious-add-on-/tree/main/invidious"
arch:
  - amd64
init: true
map:
  - share:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface"
webui: "http://[HOST]:[PORT:3000]"
options: {}
schema: {}
image: "ghcr.io/tserra30/{arch}-addon-invidious"
